In [2]:
import os
import glob
import shutil
import cv2
import sympy
import numpy as np
from PIL import Image
from sympy import symbols
from sympy.matrices import *
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [2]:
class Directories:
    def __init__(self):
        Folder_Name = ["Images_Folder","Result_Folder"]
        for i in range(len(Folder_Name)):
            if os.path.exists(Folder_Name[i]):
                pass
            else:
                os.mkdir(Folder_Name[i])
        self.Store_Path(os.getcwd(), os.path.join(os.getcwd(),"Images_Folder"), os.path.join(os.getcwd(),"Result_Folder"))                
        self.Convert_to_PNG()
        
    def Store_Path(self, Main_Folder, Path_Images_Folder, Path_Result_Folder):
        self.Main_Folder = Main_Folder
        self.Images_Folder = Path_Images_Folder
        self.Result_Folder = Path_Result_Folder
   
    def Convert_to_PNG(self):
        Image_list = ["*.png", "*.jpeg","*.jpg"]        
        for i in range(len(Image_list)):
            Image_File_Raster = glob.glob(Image_list[i])            
            for n in range(len(Image_File_Raster)):
                if ".png" in Image_File_Raster[n]:
                    shutil.move(Image_File_Raster[n], "Images_Folder")
                else:
                    Image_name = Image_File_Raster[n][::-1].split(".",1)
                    Renamed = Image_name[1][::-1]+".png"
                    os.rename(Image_File_Raster[n],Image_name[1][::-1]+".png")
                    shutil.move(Renamed, "Images_Folder")                      
Path = Directories()

In [15]:
def Convert_Image_To_Matrix():
  os.chdir(Path.Images_Folder)
  picture_name = "sample.png"
  # if picture_name in os.listdir():
  #   print("Found the picture:", picture_name)
  #   img = cv2.imread(picture_name)
  #   gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
  #   data = np.array(gray_img)/255
  #   return data
  # else:
  #   print("Picture not found.")          

In [4]:
os.chdir('c:\\Users\\QuySech\\OneDrive\\Project\\Singular value decomposition\\Singular-value-decomposition')
os.getcwd()

'c:\\Users\\QuySech\\OneDrive\\Project\\Singular value decomposition\\Singular-value-decomposition'

In [3]:
Image = cv2.imread("c:\\Users\\QuySech\\OneDrive\\Project\\Singular value decomposition\\Singular-Value-Decomposition\\Images_Folder\Screenshot 2024-09-10 162706.png")
Image1 = np.array(Image)
print(Image1)

[[[ 43  17  12]
  [ 43  17  12]
  [ 43  17  12]
  ...
  [ 47  23  19]
  [ 47  22  19]
  [ 47  22  19]]

 [[ 42  16  12]
  [ 42  16  11]
  [ 42  16  11]
  ...
  [ 47  23  19]
  [ 47  22  19]
  [ 47  23  19]]

 [[ 42  16  11]
  [ 41  16  11]
  [ 41  16  11]
  ...
  [ 48  23  20]
  [ 48  23  20]
  [ 48  23  20]]

 ...

 [[206 174 154]
  [208 173 155]
  [208 173 155]
  ...
  [227 178 156]
  [227 177 155]
  [227 177 155]]

 [[209 176 157]
  [209 176 157]
  [209 176 157]
  ...
  [227 178 157]
  [227 178 157]
  [227 178 157]]

 [[208 177 158]
  [208 177 158]
  [208 177 159]
  ...
  [226 179 159]
  [226 179 158]
  [226 180 159]]]


In [4]:
Image = cv2.imread("c:\\Users\\QuySech\\OneDrive\\Project\\Singular value decomposition\\Singular-Value-Decomposition\\Images_Folder\Screenshot 2024-09-10 162706.png")
Gray_Image = cv2.cvtColor(Image, cv2.COLOR_RGB2GRAY)
Data = np.array(Gray_Image)/255
print(Data)

# plt.imshow(img, cmap='gray')
# plt.imshow(img)

[[0.09411765 0.09411765 0.09411765 ... 0.11764706 0.11372549 0.11372549]
 [0.09019608 0.09019608 0.09019608 ... 0.11764706 0.11372549 0.11764706]
 [0.09019608 0.09019608 0.09019608 ... 0.11764706 0.11764706 0.11764706]
 ...
 [0.70980392 0.70980392 0.70980392 ... 0.74509804 0.74117647 0.74117647]
 [0.72156863 0.72156863 0.72156863 ... 0.74509804 0.74509804 0.74509804]
 [0.72156863 0.72156863 0.72156863 ... 0.74901961 0.74901961 0.74901961]]


In [ ]:
def sort(eigvaule_vector):
    dict = {}
    for x in range(len(eigvaule_vector[0])):
        dict[eigvaule_vector[0][x]] = eigvaule_vector[1][:, x]
    key = list(dict.keys())
    key = sorted(key, key=None, reverse=True)
    return {i: dict[i] for i in key}

In [ ]:
def find_eigenvalue(matrix):
    x = symbols('x')
    fun =matrix-x*sympy.eye(len(matrix[0]))
    return sympy.solve(sympy.det(fun))

def find_eigenvector(matrix):
  arr = []
  w,v = np.linalg.eigh(matrix)
  # print(w,v)
  return w,v

In [ ]:
def show_image(result,k):
  drive.mount('/content/drive')
  %cd /content/drive/MyDrive/Colab_Notebooks/SVD/result
  img_array = np.array(result, dtype=np.uint8)
  img = Image.fromarray(img_array)
  print(img_array.shape)
  if picture_name in os.listdir():
    img = cv2.imread(picture_name)

  new_location = "/content/drive/MyDrive/Colab_Notebooks/SVD/result"
  new_filename = f"aFinal_{k}.jpg"

  # Create the new folder if it doesn't exist
  if not os.path.exists(new_location):
    os.makedirs(new_location)

  # Save the image to the new location
  cv2.imwrite(os.path.join(new_location, new_filename), img_array)

In [ ]:
class math:
    def __init__(self):
        self.matrix = convert_image_to_matrix()
        # self.matrix = np.array([[1,0,1],[0,1,1]])
        self.shape = np.shape(self.matrix)
        self.k = 40
        result = self.SVD()
        show_image(result*255,self.k)


    def SVD(self):
      c,r = self.shape
      A = self.matrix
      V = []
      U = []
      print(np.shape(self.matrix))
      AtA = np.matmul(np.transpose(self.matrix),self.matrix)

      b = find_eigenvector(np.array(AtA,dtype= float))

      """turn into dict then soft in descending"""
      Newdict = sort(b)

      """now find UDV.T"""
      D = np.zeros(self.shape,dtype = 'complex_')
      r,c = self.shape
      for x in range(min(r,c)):
          D[x][x] = np.sqrt(np.abs(list(Newdict.keys())[x]))
      d = D[0:self.k,0:self.k]


      for x in Newdict.values():
          V.append(list(x))
      V = Matrix(V).T
      v = V[:,0:self.k]

      for i in range(min(self.k,r)):
        U.append((np.matmul(A,V[:,i])/D[i][i]).T[0])
      U = Matrix(U).T
      u = U[:, 0:self.k]

      # for full information preserve, find A instead
      # A = U*D*(V.T)

      # print('D = ',Matrix(d))
      # print('V =',V)
      # print('U = ',U)
      # # print('A =', A)
      # return A

      a = u * d * (v.T)

      print('D = ',Matrix(d))
      print('V =',v)
      print('U = ',u)
      print('A =', a) #overflow google presentaion anyway

      return a


if __name__ == '__main__':
    math()