In [1]:
import os, glob
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [2]:
Root = os.getcwd()
os.makedirs('Images_Folder', exist_ok=True)
os.makedirs('Result_Folder', exist_ok=True)

In [3]:
def Convert_to_PNG():
    os.chdir(os.path.join(Root,'Images_Folder'))
    image_patterns = ["*.jpeg", "*.jpg"]
    for pattern in image_patterns:
        for image_file in glob.glob(pattern):
            if not image_file.endswith(".png"):
                new_file = os.path.splitext(image_file)[0] + ".png"
                os.rename(image_file, new_file)
    os.chdir(Root)

In [4]:
def Image_Show(Image):
    plt.imshow(Image, cmap='gray')
    plt.axis('off')
    plt.show() 

In [6]:
Image = cv2.imread(os.path.join('Images_Folder','Meme.png'))

print("Kích thước ảnh gốc:", Image.shape)

Gray_Image = np.zeros((Image.shape[0], Image.shape[1])) # Tạo ma trận 0 bằng kích thước với ma trận xuất ra từ hình ảnh

for Row in range(Image.shape[0]): # chạy qua các hàng
    for Col in range(Image.shape[1]): # chạy qua các cột
        Pixel = Image[Row, Col]  # Lấy các giá trị Pixel của định dạng BRG
        Gray_Pixel = Pixel[0] * 0.114 + Pixel[1] * 0.587 + Pixel[2] * 0.299 # Chuyển sang Pixel của ảnh định dạng Gray
        Gray_Image[Row, Col] = Gray_Pixel # Thêm các giá trị vào ảnh Gray     

Kích thước ảnh gốc: (708, 720, 3)
[[116.964 116.964 116.964 ... 154.186 163.588 170.588]
 [116.964 116.964 116.964 ... 158.186 168.588 176.588]
 [116.964 116.964 116.964 ... 163.186 173.588 180.588]
 ...
 [128.861 128.861 128.861 ... 111.858 111.858 111.858]
 [128.861 128.861 128.861 ... 111.858 111.858 111.858]
 [128.861 128.861 128.861 ... 111.858 111.858 111.858]]


In [8]:
Gray_Image_3x3 = Gray_Image[0:3, 0:3]
for row in Gray_Image_3x3:
    print(row)

[116.964 116.964 116.964]
[116.964 116.964 116.964]
[116.964 116.964 116.964]
